FROM python:3.9-slim

ENV DB_HOST=172.20.0.10
ENV DB_TABLE=request
ENV DB_USER=dbuser
ENV DB_PASSWORD=password
ENV DB_NAME=data

WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY main.py ./
CMD ["python", "main.py"]
